### ISSUE TITLE
v6.4.1-v6.4.3: "Permission denied" for storage is handled incorrectly.

### ISSUE THREAD

**Issue by vi** [Tribler/tribler#1159]
```
CRITICAL 1421702639.25     minitwisted:105   MINITWISTED CRASHED
ERROR   1421702639.25     minitwisted:106   MINITWISTED CRASHED
Traceback (most recent call last):
  File "/home/vi/home/tribler/tribler/Tribler/Core/DecentralizedTracking/pymdht/core/minitwisted.py", line 103, in run2
    self.run_one_step()
  File "/home/vi/home/tribler/tribler/Tribler/Core/DecentralizedTracking/pymdht/core/minitwisted.py", line 179, in run_one_step
    datagram_received)
  File "/home/vi/home/tribler/tribler/Tribler/Core/DecentralizedTracking/pymdht/core/controller.py", line 291, in on_datagram_received
    ) = related_query.lookup_obj.on_error_received(msg, addr)
  File "/home/vi/home/tribler/tribler/Tribler/Core/DecentralizedTracking/pymdht/plugins/lookup_a4.py", line 255, in on_error_received
    logger.debug('Got error from node addr: %r' % node_addr)
TypeError: not all arguments converted during string formatting
MINITWISTED CRASHED (see logs)
```

The torrent file: http://images.kali.org/kali-linux-1.0.9a-i386.torrent

`~/.Tribler/pymdht.log`:

```
2015-01-20 00:21:32,762 CRITICAL minitwisted.py:100 - run2()
run

2015-01-20 00:23:31,743 CRITICAL minitwisted.py:100 - run2()
run

2015-01-20 00:23:59,249 CRITICAL minitwisted.py:105 - run2()
MINITWISTED CRASHED

2015-01-20 00:23:59,249 ERROR minitwisted.py:106 - run2()
MINITWISTED CRASHED
Traceback (most recent call last):
  File "/home/vi/home/tribler/tribler/Tribler/Core/DecentralizedTracking/pymdht/core/minitwisted.py", line 103, in run2
    self.run_one_step()
  File "/home/vi/home/tribler/tribler/Tribler/Core/DecentralizedTracking/pymdht/core/minitwisted.py", line 179, in run_one_step
    datagram_received)
  File "/home/vi/home/tribler/tribler/Tribler/Core/DecentralizedTracking/pymdht/core/controller.py", line 291, in on_datagram_received
    ) = related_query.lookup_obj.on_error_received(msg, addr)
  File "/home/vi/home/tribler/tribler/Tribler/Core/DecentralizedTracking/pymdht/plugins/lookup_a4.py", line 255, in on_error_received
    logger.debug('Got error from node addr: %r' % node_addr)
TypeError: not all arguments converted during string formatting
```

**Comment by vi** [comment]
Probably the same with v6.4.2-rc2 and current `devel`.

**Comment by whirm** [comment]
I think @LipuFei sent a pull request to fix this to the pymdht guy, is that right @LipuFei ?

**Comment by LipuFei** [comment]
Fixed through #1114. It was fixed in `next`

**Comment by vi** [comment]
Running Tribler from `next`, still cannot download a torrent (although error is different now):

```
pymdht: use_cache ON!!
CRITICAL 1421877115.08     minitwisted:100   run
>>>len(self._unstable_ip_port) == 4897, num_addrs: 40
GUI started
GUI ready
ERROR   1421877141.63       community:1053  Got destroy from {192.168.0.13:7759 83.165.6.77:7759} for circuit 938141837
ERROR   1421877141.63       community:1059  Got an exit socket 938141837 ('83.165.6.77', 7759)
```

**Comment by whirm** [comment]
@vi I can't see any error message there.

**Comment by vi** [comment]
But the torrent gets "Stopped on error" after some little time downloading.

**Comment by whirm** [comment]
hm...

**Comment by vi** [comment]
I have tries various versions. v6.4.1, `devel`, `next`, v6.4.2, v6.4.3 - from user's perspective it looks similar. The download starts, I see the download rate slowly going up (like usual), then "Stoped on error".

Shall I try some other mode to get more messages? (i.e. `strace` it)

**Comment by LipuFei** [comment]
Hi @vi, could modify the following code in `sesscb_states_callback()` method in `tribler_main.py` to see what error message can you get?

Change the `logger` to use `error` instead of `debug` so that you can see the error message.
```
if ds.get_status() == DLSTATUS_STOPPED_ON_ERROR:
    self._logger.debug("main: Error: %s", repr(ds.get_error()))
```

Thanks!

**Comment by vi** [comment]
Enabled this debug message, got:

    ERROR   1421928275.98    tribler_main:652   main: Error: u'Permission denied: /mnt/store2/.......'

So it is caused by wrong download location (I though it would be `TriblerDownloads`, like usual, but it offered the previous download location as default).

I think this error message should not be DEBUG-only, it should be presented to user, not only in console, but also in GUI.
