### ISSUE TITLE
Windows close button not working

### ISSUE THREAD

**Issue by ThomasdenH** [Tribler/tribler#1569]
In Tribler 6.4.3 on Windows, the close button does nothing. I would expect the program to quit or minimize to tray, but currently for me the only way to close the program (that I know of anyway) is to manually abort the process. I am on Windows 8.1 Professional.

**Comment by whirm** [comment]
I can't reproduce this (Tested on windows 8.1 pro) 
Can you reproduce this consistently? If so, what do you do to trigger the issue?
If you leave the process alone will it close by itself eventually?
Could you have a look at the log file and see if you get any error message there?

Thanks for your report!

**Comment by ThomasdenH** [comment]
After some more testing I have found the following: The window closes fine at first, but as soon as it is moved or its size has been altered the button stops working. When leaving the program running, it doesn't close within ten minutes after the button is pressed.

When looking at the log file (pymdht.log, right?), on startup, this line appears:

    2015-07-31 21:44:06,970 CRITICAL minitwisted.pyo:100 - run2()
    run

I don't think it has anything to do with the problem, since it appears both when I can and when I can't close the program. Let me know if you need more information for me, I'm glad to help.

**Comment by synctext** [comment]
thnx for helping us debug Tribler. If Tribler has been running for a day, we sometimes see that it may take a -full- minute to flush everything to disk after pressing close.

Is this the case perhaps?

**Comment by whirm** [comment]
This minitwisted CRITICAL line is bad logging from an external library (pymdht) we use due to libtorrent not exposing some DHT calls on the python bindings. Nothing to worry about.

Thanks a lot for investigating further, I'll try to reproduce it ASAP.

**Comment by ThomasdenH** [comment]
@synctext The issue appears immediately, so probably not that.

**Comment by whirm** [comment]
@ThomasdenH I really can't reproduce this with RC2. (I tried several times with the windows 2008 machine I have on the corner) Can you have a look at the log file and see if there's anything there?

**Comment by ThomasdenH** [comment]
I have tested it on 6.4.3, not the latest RC. How can I build and test Tribler on Windows?

**Comment by BmetaMax** [comment]
@ThomasdenH at last another layperson like me- I can help with this! Go here and you can download the windows installer package of the Rc2 to install: https://github.com/Tribler/tribler/releases
Another tip; uninstall tribler 643 first but don't worry your files will still be there. I installed rc2 over 643 and had weird things happen one of the dev's asked me to do a fresh install and it helped.

**Comment by whirm** [comment]
Has anybody else run into the same issue than @BmetaMax with having to manually uninstall Tribler before installing an update? The Tribler installer runs the old Tribler uninstaller before installing the new version.

**Comment by ThomasdenH** [comment]
Ah. I hadn't noticed the executable was there. I have had no problems updating. The issue is still there though. Also, all torrents seem to be stuck on building circuits. Is this just due to the fact that few people updated?

**Comment by LipuFei** [comment]
Hi @ThomasdenH. The "building circuits" problem is actually caused by the incorrectly packaged `cryptography` module. Now this problem is fixed and it will be working in the next release.

**Comment by ThomasdenH** [comment]
After some more testing I've found that I can close the program immediately after starting it. It's after the number of channels and torrents appear that the button stops functioning.

**Comment by whirm** [comment]
@ThomasdenH Could you give a shot at this build and verify that it still happens?

http://jenkins.tribler.org/job/Publish_tribler_next/133/artifact/

Thanks!

**Comment by ThomasdenH** [comment]
Unfortunately, yes, it still does.

**Comment by whirm** [comment]
@ThomasdenH Could you edit logger.conf and set all ```level=SOMETHING``` to ```DEBUG``` and reproduce the problem? 
You should get a huge log file that may give us a hint about what's going on.

**Comment by ThomasdenH** [comment]
Sure. It was too large for pastebin, but [here's a link](https://drive.google.com/file/d/0B0dXxWOn-664ZloxVTl2VjNxM2M/view?usp=sharing) to the file on Google Drive.

**Comment by whirm** [comment]
@ThomasdenH great, thanks!

**Comment by whirm** [comment]
@ThomasdenH I'm building a new RC right now which fixes a couple of nasty bugs. Could you please see if the issue persists and upload a new log if it does?

Thanks!

**Comment by ThomasdenH** [comment]
Still does it, [here's](https://www.dropbox.com/s/ut5nc39nlas8g23/tribler.exe.log?dl=0) the log.

**Comment by whirm** [comment]
Thanks!

 I'll be creating several issues with the stuff I find on your log.

**Comment by whirm** [comment]
@ThomasdenH Just to confirm, this log comes from an RC4 install, right? 
https://github.com/Tribler/tribler/releases/tag/v6.5.0-rc4

**Comment by ThomasdenH** [comment]
Yeah, that's right.

**Comment by LipuFei** [comment]
Hi @ThomasdenH, could you try this build to see if the VLC crashing issue is resolved? Thanks!
http://jenkins.tribler.org/job/Build-Tribler_WinSrvr2008R2_64_lfei/87/artifact/tribler/dist/Tribler_6.2.0-4288-g139a219.exe

**Comment by ThomasdenH** [comment]
I tested the build, [here](http://pastebin.com/xVrHx2rU)'s the log. The close button didn't work. I am not sure what crashing issue I shoud look for. The first time I started Tribler a crash did occur while the circuits were still building.

**Comment by whirm** [comment]
@ThomasdenH could you have a run at this build and upload the new log? http://jenkins.tribler.org/job/Publish_tribler_next/144/artifact/Tribler_6.5.0-rc4-23-gbbd3530.exe 

It contains a fix for the LevelDB errors and some extra debug info for the VLC crash.

Let's see if we can figure out the VLC problem as we can't reproduce it on any of the test machines we have.

Thanks!

**Comment by ThomasdenH** [comment]
It says the integrity check has failed upon starting the installer. Also, I'm not sure what the VLC crash is, is the video player crashing the reason the close button isn't working?

**Comment by whirm** [comment]
If the integrity check failed, it means the download was corrupted, I've checked the installer and it's fine.

I don't know if the VLC failure it's related or not.

**Comment by ThomasdenH** [comment]
I can't download the installer it seems like. I'm not sure wether it is my internt connection or something else, but the download keeps getting interrupted before it finishes, resulting in a corrupted file.

**Comment by whirm** [comment]
That's weird, let me see if I can upload it somewhere else.

**Comment by whirm** [comment]
@ThomasdenH: 
https://mega.nz/#!6gpzHaQJ!CqQv3HX8N6EpZgp33B_ZArwdKkB5cgSnDpnO5OvmQB0

**Comment by ThomasdenH** [comment]
Thanks for that. [Here](https://www.dropbox.com/s/55l4n9n7ql8kspt/tribler.exe%20-%20kopie.log?dl=0)'s the new log.

**Comment by whirm** [comment]
Content of the log, for convenience:
```
ERROR   1441281935.26      VLCWrapper:161   failed to create VLC instance: None
Traceback (most recent call last):
  File "wx\_misc.pyo", line 1358, in Notify
  File "wx\_core.pyo", line 14771, in Notify
  File "Tribler\Core\Video\VLCWrapper.pyo", line 64, in _init_vlc
  File "Tribler\Core\Video\VLCWrapper.pyo", line 22, in invoke_func
  File "Tribler\Core\Video\VLCWrapper.pyo", line 162, in get_vlc_mediactrl
  File "Tribler\vlc.pyo", line 4972, in libvlc_media_player_new
WindowsError: exception: access violation reading 0x00000000
Traceback (most recent call last):
  File "Tribler\Main\vwxGUI\MainFrame.pyo", line 841, in OnCloseWindow
  File "Tribler\Main\vwxGUI\__init__.pyo", line 128, in invoke_func
    
  File "Tribler\Main\vwxGUI\EmbeddedPlayer.pyo", line 414, in Stop
  File "Tribler\Core\Video\VLCWrapper.pyo", line 22, in invoke_func
  File "Tribler\Core\Video\VLCWrapper.pyo", line 194, in stop
  File "Tribler\vlc.pyo", line 5085, in libvlc_media_player_stop
WindowsError: exception: access violation reading 0x0000001C
```

**Comment by whirm** [comment]
@ThomasdenH BTW, do you have VLC installed on your machine?

**Comment by ThomasdenH** [comment]
Yes, I do.

**Comment by LipuFei** [comment]
Hi @ThomasdenH, I think we have found the problem with your vlc. Could you try this build? Thanks!
http://jenkins.tribler.org/job/Build-Tribler_WinSrvr2008R2_64_next/54/artifact/tribler/dist/Tribler_6.5.0-rc4-33-g39553aa.exe

**Comment by ThomasdenH** [comment]
Tribler closes! I did get an error when it was this is the log:

```
Traceback (most recent call last):
  File "Tribler\Core\Video\utils.pyo", line 119, in return_feasible_playback_modes
  File "Tribler\vlc.pyo", line 168, in <module>
  File "Tribler\vlc.pyo", line 148, in find_lib
  File "ctypes\__init__.pyo", line 365, in __init__
WindowsError: [Error 127] Kan opgegeven procedure niet vinden
Traceback (most recent call last):
  File "Tribler\Core\Video\utils.pyo", line 119, in return_feasible_playback_modes
  File "Tribler\vlc.pyo", line 168, in <module>
  File "Tribler\vlc.pyo", line 148, in find_lib
  File "ctypes\__init__.pyo", line 365, in __init__
WindowsError: [Error 127] Kan opgegeven procedure niet vinden
Traceback (most recent call last):
  File "Tribler\Core\Video\utils.pyo", line 119, in return_feasible_playback_modes
  File "Tribler\vlc.pyo", line 168, in <module>
  File "Tribler\vlc.pyo", line 148, in find_lib
  File "ctypes\__init__.pyo", line 365, in __init__
WindowsError: [Error 127] Kan opgegeven procedure niet vinden
Traceback (most recent call last):
  File "Tribler\Core\Video\utils.pyo", line 119, in return_feasible_playback_modes
  File "Tribler\vlc.pyo", line 168, in <module>
  File "Tribler\vlc.pyo", line 148, in find_lib
  File "ctypes\__init__.pyo", line 365, in __init__
WindowsError: [Error 127] Kan opgegeven procedure niet vinden
Traceback (most recent call last):
  File "Tribler\Core\Video\utils.pyo", line 119, in return_feasible_playback_modes
  File "Tribler\vlc.pyo", line 168, in <module>
  File "Tribler\vlc.pyo", line 148, in find_lib
  File "ctypes\__init__.pyo", line 365, in __init__
WindowsError: [Error 127] Kan opgegeven procedure niet vinden
Traceback (most recent call last):
  File "Tribler\Core\Video\utils.pyo", line 119, in return_feasible_playback_modes
  File "Tribler\vlc.pyo", line 168, in <module>
  File "Tribler\vlc.pyo", line 148, in find_lib
  File "ctypes\__init__.pyo", line 365, in __init__
WindowsError: [Error 127] Kan opgegeven procedure niet vinden
```

**Comment by LipuFei** [comment]
Hi @ThomasdenH, could you install tribler in a path with ascii characters only and try again? Thanks!

**Comment by ThomasdenH** [comment]
I have it installed on a path with ASCII characters only. Should I use a path without spaces?

**Comment by LipuFei** [comment]
@ThomasdenH spaces should be fine. We have just made a fix for this installation path issue. So the next release should work for you, regardless of where you install it.

**Comment by ThomasdenH** [comment]
Ok, I will wait for that.

**Comment by whirm** [comment]
@ThomasdenH Could you see if [this](https://jenkins.tribler.org/job/Build-Tribler_WinSrvr2008R2_64_emilon/65/) build and see if you still have issues, I've been fixing and testing Tribler on Windows 10 for a few weeks and I've never seen this issue.

**Comment by ThomasdenH** [comment]
I still have the problem. I have deleted the log, so this is the output from only this build:

```
ERROR   1445887596.09      VLCWrapper:161   failed to create VLC instance: None
Traceback (most recent call last):
  File "wx\_misc.pyo", line 1358, in Notify
  File "wx\_core.pyo", line 14771, in Notify
  File "Tribler\Core\Video\VLCWrapper.pyo", line 64, in _init_vlc
  File "Tribler\Core\Video\VLCWrapper.pyo", line 22, in invoke_func
  File "Tribler\Core\Video\VLCWrapper.pyo", line 162, in get_vlc_mediactrl
  File "Tribler\vlc.pyo", line 4972, in libvlc_media_player_new
WindowsError: exception: access violation reading 0x00000000
ERROR   1445887598.12    GuiDBHandler:253   'Traceback (most recent call last):\n  File "Tribler\\Main\\Utility\\GuiDBHandler.pyo", line 121, in wrapper\n  File "Tribler\\Main\\tribler_main.pyo", line 669, in loadSessionCheckpoint\n  File "Tribler\\Core\\Session.pyo", line 411, in load_checkpoint\n  File "Tribler\\Core\\APIImplementation\\LaunchManyCore.pyo", line 454, in load_checkpoint\n  File "Tribler\\Core\\APIImplementation\\LaunchManyCore.pyo", line 508, in resume_download\nAttributeError: \'NoneType\' object has no attribute \'get\'\n'
ERROR   1445887598.12    GuiDBHandler:270   'Traceback (most recent call last):\n  File "Tribler\\Main\\Utility\\GuiDBHandler.pyo", line 121, in wrapper\n  File "Tribler\\Main\\tribler_main.pyo", line 669, in loadSessionCheckpoint\n  File "Tribler\\Core\\Session.pyo", line 411, in load_checkpoint\n  File "Tribler\\Core\\APIImplementation\\LaunchManyCore.pyo", line 454, in load_checkpoint\n  File "Tribler\\Core\\APIImplementation\\LaunchManyCore.pyo", line 508, in resume_download\nAttributeError: \'NoneType\' object has no attribute \'get\'\n'
Traceback (most recent call last):
  File "Tribler\Main\vwxGUI\MainFrame.pyo", line 846, in OnCloseWindow
  File "Tribler\Main\vwxGUI\__init__.pyo", line 128, in invoke_func
    
  File "Tribler\Main\vwxGUI\EmbeddedPlayer.pyo", line 414, in Stop
  File "Tribler\Core\Video\VLCWrapper.pyo", line 22, in invoke_func
  File "Tribler\Core\Video\VLCWrapper.pyo", line 194, in stop
  File "Tribler\vlc.pyo", line 5085, in libvlc_media_player_stop
WindowsError: exception: access violation reading 0x0000001C
```

Let me know if I need to do some additional testing.

**Comment by whirm** [comment]
@ThomasdenH Ok, I'd say there's an interaction with your locally installed VLC, Could you uninstall it just to test if Tribler works OK without it?

Thanks!

**Comment by ThomasdenH** [comment]
I uninstalled VLC, but I still get an error and cannot close the program:

```
ERROR   1446031645.77      VLCWrapper:161   failed to create VLC instance: None
Traceback (most recent call last):
  File "wx\_misc.pyo", line 1358, in Notify
  File "wx\_core.pyo", line 14771, in Notify
  File "Tribler\Core\Video\VLCWrapper.pyo", line 64, in _init_vlc
  File "Tribler\Core\Video\VLCWrapper.pyo", line 22, in invoke_func
  File "Tribler\Core\Video\VLCWrapper.pyo", line 162, in get_vlc_mediactrl
  File "Tribler\vlc.pyo", line 4972, in libvlc_media_player_new
WindowsError: exception: access violation reading 0x00000000
ERROR   1446031648.01    GuiDBHandler:253   'Traceback (most recent call last):\n  File "Tribler\\Main\\Utility\\GuiDBHandler.pyo", line 121, in wrapper\n  File "Tribler\\Main\\tribler_main.pyo", line 669, in loadSessionCheckpoint\n  File "Tribler\\Core\\Session.pyo", line 411, in load_checkpoint\n  File "Tribler\\Core\\APIImplementation\\LaunchManyCore.pyo", line 454, in load_checkpoint\n  File "Tribler\\Core\\APIImplementation\\LaunchManyCore.pyo", line 508, in resume_download\nAttributeError: \'NoneType\' object has no attribute \'get\'\n'
ERROR   1446031648.01    GuiDBHandler:270   'Traceback (most recent call last):\n  File "Tribler\\Main\\Utility\\GuiDBHandler.pyo", line 121, in wrapper\n  File "Tribler\\Main\\tribler_main.pyo", line 669, in loadSessionCheckpoint\n  File "Tribler\\Core\\Session.pyo", line 411, in load_checkpoint\n  File "Tribler\\Core\\APIImplementation\\LaunchManyCore.pyo", line 454, in load_checkpoint\n  File "Tribler\\Core\\APIImplementation\\LaunchManyCore.pyo", line 508, in resume_download\nAttributeError: \'NoneType\' object has no attribute \'get\'\n'
Traceback (most recent call last):
  File "Tribler\Main\vwxGUI\MainFrame.pyo", line 846, in OnCloseWindow
  File "Tribler\Main\vwxGUI\__init__.pyo", line 128, in invoke_func
    
  File "Tribler\Main\vwxGUI\EmbeddedPlayer.pyo", line 414, in Stop
  File "Tribler\Core\Video\VLCWrapper.pyo", line 22, in invoke_func
  File "Tribler\Core\Video\VLCWrapper.pyo", line 194, in stop
  File "Tribler\vlc.pyo", line 5085, in libvlc_media_player_stop
WindowsError: exception: access violation reading 0x0000001C
```

**Comment by whirm** [comment]
I've tried installing VLC, starting Tribler with over 200 downloads, stopping, uninstalling VLC, starting again and it just works on my Windows 10 testing machine.

Are/where you running the latest VLC version? Tribler bundles 2.1.X I'll upgrade to the latest version so you can see if works then.

Could you download the 32 bit version of dependency walker from www.dependencywalker.com and check if `libvlc.dll` and `libvlccore.dll` have any missing dependency on your machine?

The VLC error seems unrelated to the download state restoring error that we see afterwards: Tribler having issues with loading some of the download state files and then doing the wrong thing about it. I'll fix that one but I want to see if we can deal with the vlc stuff first.

This build should not try to further initialize the video player if the first initialization phase fails, which will not fix anything but you will not get the stacktrace resulting of Tribler ignoring the first failure, just an error message on the log.

https://jenkins.tribler.org/job/Build-Tribler_WinSrvr2008R2_64_emilon/67/

BTW: The latest builds move Tribler.exe.log to Tribler.exe.old.log at each startup, so you don't need to delete the log file anymore :)

**Comment by whirm** [comment]
This build bundles the latest libvlc and python bindings.
Could you test it in case it helps with the VLC issue?
https://jenkins.tribler.org/job/Build-Tribler_WinSrvr2008R2_64_emilon/68/

**Comment by ThomasdenH** [comment]
I tested the latest build (#68), but the problem wasn't fixed. I ran dependency walker and quite a number of files couldn't be found. I exported the images: [libvlc](https://www.dropbox.com/s/12cug6s6zdt9zgp/libvlc.dwi?dl=0) and [libvlccore](https://www.dropbox.com/s/u188mgy072obrjx/libvlccore.dwi?dl=0).

**Comment by whirm** [comment]
It looks exactly like the one on my testing machine (It's missing some DLLs which are bundled with Tribler but they should be found at run time).

Could you run this build and paste the log? 

https://jenkins.tribler.org/job/Build-Tribler_WinSrvr2008R2_64_emilon/69/

I've added some debug prints so I can make sure that the PATH var makes sense in your system.

**Comment by ThomasdenH** [comment]
This is the log:
```
ERROR   1446056010.85      VLCWrapper:161   failed to create VLC instance: None
ERROR   1446056010.85      VLCWrapper:162   PATH is: u"C:\\Program Files (x86)\\Google\\Chrome\\Application;C:\\Program Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS Client\\;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\Program Files (x86)\\ATI Technologies\\ATI.ACE\\Core-Static;C:\\Program Files (x86)\\Git\\cmd;%LUXRENDER_ROOT%;C:\\Program Files (x86)\\Windows Kits\\8.1\\Windows Performance Toolkit\\;C:\\Program Files\\Microsoft SQL Server\\110\\Tools\\Binn\\;C:\\Program Files (x86)\\Microsoft SDKs\\TypeScript\\1.0\\;C:\\Program Files\\Microsoft SQL Server\\120\\Tools\\Binn\\;C:\\Program Files (x86)\\AMD\\ATI.ACE\\Core-Static;C:\\Program Files\\Calibre2\\;C:\\Program Files\\nodejs\\;C:\\Program Files (x86)\\QuickTime\\QTSystem\\;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;D:\\Programma's\\MiKTeX\\miktex\\bin\\x64\\;C:\\Program Files (x86)\\Skype\\Phone\\;D:\\Programma's\\Rust\\bin;C:\\Users\\Thomas\\AppData\\Roaming\\npm;C:\\Program Files\\Python;C:\\Program Files\\Python\\Scripts;C:\\Program Files (x86)\\Tribler;C:\\Program Files (x86)\\Tribler\\vlc"
Traceback (most recent call last):
  File "wx\_misc.pyo", line 1358, in Notify
  File "wx\_core.pyo", line 14771, in Notify
  File "Tribler\Core\Video\VLCWrapper.pyo", line 64, in _init_vlc
  File "Tribler\Core\Video\VLCWrapper.pyo", line 22, in invoke_func
  File "Tribler\Core\Video\VLCWrapper.pyo", line 163, in get_vlc_mediactrl
  File "os.pyo", line 425, in __getitem__
    
KeyError: 'PYTHONPATH'
ERROR   1446056012.89    GuiDBHandler:253   'Traceback (most recent call last):\n  File "Tribler\\Main\\Utility\\GuiDBHandler.pyo", line 121, in wrapper\n  File "Tribler\\Main\\tribler_main.pyo", line 669, in loadSessionCheckpoint\n  File "Tribler\\Core\\Session.pyo", line 411, in load_checkpoint\n  File "Tribler\\Core\\APIImplementation\\LaunchManyCore.pyo", line 454, in load_checkpoint\n  File "Tribler\\Core\\APIImplementation\\LaunchManyCore.pyo", line 508, in resume_download\nAttributeError: \'NoneType\' object has no attribute \'get\'\n'
ERROR   1446056012.89    GuiDBHandler:270   'Traceback (most recent call last):\n  File "Tribler\\Main\\Utility\\GuiDBHandler.pyo", line 121, in wrapper\n  File "Tribler\\Main\\tribler_main.pyo", line 669, in loadSessionCheckpoint\n  File "Tribler\\Core\\Session.pyo", line 411, in load_checkpoint\n  File "Tribler\\Core\\APIImplementation\\LaunchManyCore.pyo", line 454, in load_checkpoint\n  File "Tribler\\Core\\APIImplementation\\LaunchManyCore.pyo", line 508, in resume_download\nAttributeError: \'NoneType\' object has no attribute \'get\'\n'
Traceback (most recent call last):
  File "Tribler\Main\vwxGUI\MainFrame.pyo", line 846, in OnCloseWindow
  File "Tribler\Main\vwxGUI\__init__.pyo", line 128, in invoke_func
    
  File "Tribler\Main\vwxGUI\EmbeddedPlayer.pyo", line 414, in Stop
  File "Tribler\Core\Video\VLCWrapper.pyo", line 22, in invoke_func
  File "Tribler\Core\Video\VLCWrapper.pyo", line 198, in stop
  File "Tribler\vlc.pyo", line 5159, in libvlc_media_player_stop
WindowsError: exception: access violation reading 0x0000001C
```

**Comment by whirm** [comment]
@ThomasdenH please tell me this one works :D
https://jenkins.tribler.org/job/Build-Tribler_WinSrvr2008R2_64_emilon/71/

**Comment by ThomasdenH** [comment]
Closing works, but now I get a 'Tribler stopped working' from Windows, with the following log file:
```
Traceback (most recent call last):
  File "Tribler\Core\Video\utils.pyo", line 125, in return_feasible_playback_modes
  File "Tribler\vlc.pyo", line 173, in <module>
  File "Tribler\vlc.pyo", line 153, in find_lib
  File "ctypes\__init__.pyo", line 365, in __init__
WindowsError: [Error 127] Kan opgegeven procedure niet vinden
Traceback (most recent call last):
  File "Tribler\Core\Video\utils.pyo", line 125, in return_feasible_playback_modes
  File "Tribler\vlc.pyo", line 173, in <module>
  File "Tribler\vlc.pyo", line 153, in find_lib
  File "ctypes\__init__.pyo", line 365, in __init__
WindowsError: [Error 127] Kan opgegeven procedure niet vinden
Traceback (most recent call last):
  File "Tribler\Core\Video\utils.pyo", line 125, in return_feasible_playback_modes
  File "Tribler\vlc.pyo", line 173, in <module>
  File "Tribler\vlc.pyo", line 153, in find_lib
  File "ctypes\__init__.pyo", line 365, in __init__
WindowsError: [Error 127] Kan opgegeven procedure niet vinden
ERROR   1446117669.92    GuiDBHandler:253   'Traceback (most recent call last):\n  File "Tribler\\Main\\Utility\\GuiDBHandler.pyo", line 121, in wrapper\n  File "Tribler\\Main\\tribler_main.pyo", line 669, in loadSessionCheckpoint\n  File "Tribler\\Core\\Session.pyo", line 411, in load_checkpoint\n  File "Tribler\\Core\\APIImplementation\\LaunchManyCore.pyo", line 454, in load_checkpoint\n  File "Tribler\\Core\\APIImplementation\\LaunchManyCore.pyo", line 508, in resume_download\nAttributeError: \'NoneType\' object has no attribute \'get\'\n'
ERROR   1446117669.92    GuiDBHandler:270   'Traceback (most recent call last):\n  File "Tribler\\Main\\Utility\\GuiDBHandler.pyo", line 121, in wrapper\n  File "Tribler\\Main\\tribler_main.pyo", line 669, in loadSessionCheckpoint\n  File "Tribler\\Core\\Session.pyo", line 411, in load_checkpoint\n  File "Tribler\\Core\\APIImplementation\\LaunchManyCore.pyo", line 454, in load_checkpoint\n  File "Tribler\\Core\\APIImplementation\\LaunchManyCore.pyo", line 508, in resume_download\nAttributeError: \'NoneType\' object has no attribute \'get\'\n'
```

**Comment by whirm** [comment]
This one doesn't fix anything but adds some debug prints to see which libvlc.dll it's finding that's not good.

https://jenkins.tribler.org/job/Build-Tribler_WinSrvr2008R2_64_emilon/74/

**Comment by ThomasdenH** [comment]
This is the log:
```
Found libvlc.dll at: u'C:\\Program Files (x86)\\Tribler\\vlc\\libvlc.dll'
Plugin path at: u'C:\\Program Files (x86)\\Tribler\\vlc'
Traceback (most recent call last):
  File "Tribler\Core\Video\utils.pyo", line 125, in return_feasible_playback_modes
  File "Tribler\vlc.pyo", line 175, in <module>
  File "Tribler\vlc.pyo", line 155, in find_lib
  File "ctypes\__init__.pyo", line 365, in __init__
WindowsError: [Error 127] Kan opgegeven procedure niet vinden
Found libvlc.dll at: u'C:\\Program Files (x86)\\Tribler\\vlc\\libvlc.dll'
Plugin path at: u'C:\\Program Files (x86)\\Tribler\\vlc'
Traceback (most recent call last):
  File "Tribler\Core\Video\utils.pyo", line 125, in return_feasible_playback_modes
  File "Tribler\vlc.pyo", line 175, in <module>
  File "Tribler\vlc.pyo", line 155, in find_lib
  File "ctypes\__init__.pyo", line 365, in __init__
WindowsError: [Error 127] Kan opgegeven procedure niet vinden
Found libvlc.dll at: u'C:\\Program Files (x86)\\Tribler\\vlc\\libvlc.dll'
Plugin path at: u'C:\\Program Files (x86)\\Tribler\\vlc'
Traceback (most recent call last):
  File "Tribler\Core\Video\utils.pyo", line 125, in return_feasible_playback_modes
  File "Tribler\vlc.pyo", line 175, in <module>
  File "Tribler\vlc.pyo", line 155, in find_lib
  File "ctypes\__init__.pyo", line 365, in __init__
WindowsError: [Error 127] Kan opgegeven procedure niet vinden
ERROR   1446149525.11    GuiDBHandler:253   'Traceback (most recent call last):\n  File "Tribler\\Main\\Utility\\GuiDBHandler.pyo", line 121, in wrapper\n  File "Tribler\\Main\\tribler_main.pyo", line 669, in loadSessionCheckpoint\n  File "Tribler\\Core\\Session.pyo", line 411, in load_checkpoint\n  File "Tribler\\Core\\APIImplementation\\LaunchManyCore.pyo", line 454, in load_checkpoint\n  File "Tribler\\Core\\APIImplementation\\LaunchManyCore.pyo", line 508, in resume_download\nAttributeError: \'NoneType\' object has no attribute \'get\'\n'
ERROR   1446149525.11    GuiDBHandler:270   'Traceback (most recent call last):\n  File "Tribler\\Main\\Utility\\GuiDBHandler.pyo", line 121, in wrapper\n  File "Tribler\\Main\\tribler_main.pyo", line 669, in loadSessionCheckpoint\n  File "Tribler\\Core\\Session.pyo", line 411, in load_checkpoint\n  File "Tribler\\Core\\APIImplementation\\LaunchManyCore.pyo", line 454, in load_checkpoint\n  File "Tribler\\Core\\APIImplementation\\LaunchManyCore.pyo", line 508, in resume_download\nAttributeError: \'NoneType\' object has no attribute \'get\'\n'
```

**Comment by whirm** [comment]
Ok, so it's definitely finding the right dll.

Just to rule out some weird interaction with the system's language: Could you switch your system to English, reboot and try again?

http://ccm.net/faq/28761-windows-8-1-how-to-change-the-language-settings

Thanks!

**Comment by ThomasdenH** [comment]
Sure. Here's the log:
```
Found libvlc.dll at: u'C:\\Program Files (x86)\\Tribler\\vlc\\libvlc.dll'
Plugin path at: u'C:\\Program Files (x86)\\Tribler\\vlc'
Traceback (most recent call last):
  File "Tribler\Core\Video\utils.pyo", line 125, in return_feasible_playback_modes
  File "Tribler\vlc.pyo", line 175, in <module>
  File "Tribler\vlc.pyo", line 155, in find_lib
  File "ctypes\__init__.pyo", line 365, in __init__
WindowsError: [Error 127] The specified procedure could not be found
Found libvlc.dll at: u'C:\\Program Files (x86)\\Tribler\\vlc\\libvlc.dll'
Plugin path at: u'C:\\Program Files (x86)\\Tribler\\vlc'
Traceback (most recent call last):
  File "Tribler\Core\Video\utils.pyo", line 125, in return_feasible_playback_modes
  File "Tribler\vlc.pyo", line 175, in <module>
  File "Tribler\vlc.pyo", line 155, in find_lib
  File "ctypes\__init__.pyo", line 365, in __init__
WindowsError: [Error 127] The specified procedure could not be found
Found libvlc.dll at: u'C:\\Program Files (x86)\\Tribler\\vlc\\libvlc.dll'
Plugin path at: u'C:\\Program Files (x86)\\Tribler\\vlc'
Traceback (most recent call last):
  File "Tribler\Core\Video\utils.pyo", line 125, in return_feasible_playback_modes
  File "Tribler\vlc.pyo", line 175, in <module>
  File "Tribler\vlc.pyo", line 155, in find_lib
  File "ctypes\__init__.pyo", line 365, in __init__
WindowsError: [Error 127] The specified procedure could not be found
ERROR   1446292845.97    GuiDBHandler:253   'Traceback (most recent call last):\n  File "Tribler\\Main\\Utility\\GuiDBHandler.pyo", line 121, in wrapper\n  File "Tribler\\Main\\tribler_main.pyo", line 669, in loadSessionCheckpoint\n  File "Tribler\\Core\\Session.pyo", line 411, in load_checkpoint\n  File "Tribler\\Core\\APIImplementation\\LaunchManyCore.pyo", line 454, in load_checkpoint\n  File "Tribler\\Core\\APIImplementation\\LaunchManyCore.pyo", line 508, in resume_download\nAttributeError: \'NoneType\' object has no attribute \'get\'\n'
ERROR   1446292845.97    GuiDBHandler:270   'Traceback (most recent call last):\n  File "Tribler\\Main\\Utility\\GuiDBHandler.pyo", line 121, in wrapper\n  File "Tribler\\Main\\tribler_main.pyo", line 669, in loadSessionCheckpoint\n  File "Tribler\\Core\\Session.pyo", line 411, in load_checkpoint\n  File "Tribler\\Core\\APIImplementation\\LaunchManyCore.pyo", line 454, in load_checkpoint\n  File "Tribler\\Core\\APIImplementation\\LaunchManyCore.pyo", line 508, in resume_download\nAttributeError: \'NoneType\' object has no attribute \'get\'\n'
```

**Comment by whirm** [comment]
Ok, let's just trace Tribler's startup so we can see which dll on the chain it's failing to load for you.

Could you download/unzip process monitor: https://technet.microsoft.com/en-us/sysinternals/bb896645

Then:

1: Start it, go to `Filter > Filter...` and add a "Process name is tribler.exe then include" filter.
2: Start Tribler
3: When it crashes, go back to process monitor and click on `File > Save` and save the log with the default params and attach it to this issue?

**Comment by ThomasdenH** [comment]
The file is [here](https://drive.google.com/file/d/0B0dXxWOn-664MFVhU2lRWXAyT28/view?usp=sharing).

**Comment by whirm** [comment]
Ok, that one should really fix it for you:

http://jenkins.tribler.org/job/Build-Tribler_WinSrvr2008R2_64_emilon/83/

If by any reason it doesn't, please, do the process monitor thing again.

**Comment by ThomasdenH** [comment]
Tribler closes, but while it does, it still displays a notification that an error has occured. The logfile contains this:

```
Traceback (most recent call last):
  File "Tribler\Core\Video\utils.pyo", line 128, in return_feasible_playback_modes
  File "Tribler\vlc.pyo", line 168, in <module>
  File "Tribler\vlc.pyo", line 148, in find_lib
  File "ctypes\__init__.pyo", line 365, in __init__
WindowsError: [Error 127] Kan opgegeven procedure niet vinden
Traceback (most recent call last):
  File "Tribler\Core\Video\utils.pyo", line 128, in return_feasible_playback_modes
  File "Tribler\vlc.pyo", line 168, in <module>
  File "Tribler\vlc.pyo", line 148, in find_lib
  File "ctypes\__init__.pyo", line 365, in __init__
WindowsError: [Error 127] Kan opgegeven procedure niet vinden
Traceback (most recent call last):
  File "Tribler\Core\Video\utils.pyo", line 128, in return_feasible_playback_modes
  File "Tribler\vlc.pyo", line 168, in <module>
  File "Tribler\vlc.pyo", line 148, in find_lib
  File "ctypes\__init__.pyo", line 365, in __init__
WindowsError: [Error 127] Kan opgegeven procedure niet vinden
Exception in thread Notifier-timer-activities:
Traceback (most recent call last):
  File "threading.pyo", line 810, in __bootstrap_inner
  File "threading.pyo", line 1082, in run
  File "Tribler\Core\CacheDB\Notifier.pyo", line 103, in doQueue
  File "Tribler\Core\Utilities\twisted_utils.pyo", line 46, in callInThreadPool
  File "Tribler\Core\Utilities\twisted_utils.pyo", line 56, in isInThreadPool
AttributeError: 'NoneType' object has no attribute 'threads'
```

I also had another error occur while the program was running. I did add a magnet link, but it might not have been immediately afterwards.

```
Traceback (most recent call last):
  File "Tribler\Core\Video\utils.pyo", line 128, in return_feasible_playback_modes
  File "Tribler\vlc.pyo", line 168, in <module>
  File "Tribler\vlc.pyo", line 148, in find_lib
  File "ctypes\__init__.pyo", line 365, in __init__
WindowsError: [Error 127] Kan opgegeven procedure niet vinden
Traceback (most recent call last):
  File "Tribler\Core\Video\utils.pyo", line 128, in return_feasible_playback_modes
  File "Tribler\vlc.pyo", line 168, in <module>
  File "Tribler\vlc.pyo", line 148, in find_lib
  File "ctypes\__init__.pyo", line 365, in __init__
WindowsError: [Error 127] Kan opgegeven procedure niet vinden
Traceback (most recent call last):
  File "Tribler\Core\Video\utils.pyo", line 128, in return_feasible_playback_modes
  File "Tribler\vlc.pyo", line 168, in <module>
  File "Tribler\vlc.pyo", line 148, in find_lib
  File "ctypes\__init__.pyo", line 365, in __init__
WindowsError: [Error 127] Kan opgegeven procedure niet vinden
Unable to rename the log file!
ERROR   1446900915.02             log:443   Unhandled Error
Traceback (most recent call last):
  File "threading.pyo", line 763, in run
    
  File "Tribler\Core\Utilities\twisted_thread.pyo", line 55, in _reactor_runner
    
  File "twisted\internet\base.pyo", line 1192, in run
    
  File "twisted\internet\base.pyo", line 1201, in mainLoop
    
--- <exception caught here> ---
  File "twisted\internet\base.pyo", line 824, in runUntilCurrent
    
  File "Tribler\Core\Libtorrent\LibtorrentMgr.pyo", line 434, in _task_process_alerts
    
  File "Tribler\Core\Libtorrent\LibtorrentMgr.pyo", line 289, in process_alert
    
  File "Tribler\Core\Libtorrent\__init__.pyo", line 13, in invoke_func
    
  File "Tribler\Core\Libtorrent\LibtorrentDownloadImpl.pyo", line 409, in process_alert
    
  File "Tribler\Core\Libtorrent\LibtorrentDownloadImpl.pyo", line 436, in on_metadata_received_alert
    
exceptions.RuntimeError: invalid torrent handle used

Unhandled Error
Traceback (most recent call last):
  File "threading.pyo", line 763, in run
    
  File "Tribler\Core\Utilities\twisted_thread.pyo", line 55, in _reactor_runner
    
  File "twisted\internet\base.pyo", line 1192, in run
    
  File "twisted\internet\base.pyo", line 1201, in mainLoop
    
--- <exception caught here> ---
  File "twisted\internet\base.pyo", line 824, in runUntilCurrent
    
  File "Tribler\Core\Libtorrent\LibtorrentMgr.pyo", line 434, in _task_process_alerts
    
  File "Tribler\Core\Libtorrent\LibtorrentMgr.pyo", line 289, in process_alert
    
  File "Tribler\Core\Libtorrent\__init__.pyo", line 13, in invoke_func
    
  File "Tribler\Core\Libtorrent\LibtorrentDownloadImpl.pyo", line 409, in process_alert
    
  File "Tribler\Core\Libtorrent\LibtorrentDownloadImpl.pyo", line 436, in on_metadata_received_alert
    
exceptions.RuntimeError: invalid torrent handle used
ERROR   1446900921.99 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900922.01 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900922.05 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900922.06 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900929.27 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900933.15 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900933.15 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900934.37 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900934.44 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900934.93 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900935.41 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900936.11 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900936.30 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900936.55 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900937.01 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900937.05 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900937.35 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900937.38 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900951.65 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900953.17 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900953.29 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900955.09 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900955.67 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900955.72 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900957.17 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900957.96 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900958.74 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900958.74 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900959.14 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900960.31 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900962.15 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900962.31 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900963.39 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900965.44 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900965.45 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900966.01 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900966.50 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900967.01 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900969.05 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900969.57 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900970.10 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900970.11 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900971.66 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900973.33 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900974.15 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900975.44 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900975.62 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900976.42 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900979.57 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900981.43 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900983.72 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900984.29 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900984.74 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900987.51 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900987.52 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900987.52 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900988.51 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900988.56 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900990.70 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900991.74 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900991.74 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900991.74 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900993.80 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900994.82 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900996.27 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900996.72 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900996.99 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900998.01 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446900999.57 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446901000.31 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446901000.32 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446901003.20 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446901003.83 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446901004.45 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446901004.58 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446901004.58 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446901004.96 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446901005.81 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446901007.60 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446901007.78 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446901008.97 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446901009.30 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446901010.01 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446901011.87 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446901012.94 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
ERROR   1446901013.23 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0
```

I have a feeling that my Tribler data is corrupted in some way, especially since I have possibly downgraded to an incompatible version (although I am not certain). How can I reset the torrent settings?

I also ran Process Monitor, and that file is [here](https://drive.google.com/file/d/0B0dXxWOn-664Vk5VVjNtLTB2YnM/view?usp=sharing).

**Comment by whirm** [comment]
This one should work for you.
https://jenkins.tribler.org/job/Build-Tribler_WinSrvr2008R2_64_emilon/84/

Turns out you have old vlc DLLs in `sysWOW64` dir and windows will always look there before loading our stuff. So now we are manually loading our bundled `libvlc.dll` and `libvlccore.dll` to make sure this can't happen.

**Comment by whirm** [comment]
It looks like preloading `libvlcore.dll` would trigger a lookup for `libvlc.dll` for some reason. I've gone through a different approach now and even putting some dlls in the SysWOW64 dir like you have and it works fine.

Could you try this:

http://jenkins.tribler.org/job/Build-Tribler_WinSrvr2008R2_64_emilon/104/

And see if it finally works? Otherwise do the process monitor thing again. For now I'm interested in fixing the libvlc stuff, after that we can take care of the rest.

About resetting the settings, have a look at this post on the forums:

http://forum.tribler.org/t/tribler-directory-structure-and-description/3217

Thanks again!

**Comment by ThomasdenH** [comment]
It does close, thanks very much! I think I fixed the other issue by deleting some unnecessary files, too.

**Comment by whirm** [comment]
Great! glad to read that! :D

**Comment by Lcstyle** [comment]
I'm still having similar behavior on windows 10 install of 6.5.0

When exiting Tribler 6.5.0, Windows says the program has crashed, and I get a message about looking for the log, the log just contains the same message repeated :

ERROR   1457360042.62 tunnel_community:1095  cannot exit data, destination is 0.0.0.0:0

**Comment by whirm** [comment]
Could you please create a new issue for that?

Thanks!
