### ISSUE TITLE
6.5.0.RC6 Destination location not working.

### ISSUE THREAD

**Issue by Nubro01** [Tribler/tribler#1710]
When one picks a location for the files to be downloaded, the last folder is not used, so e:\Videos\Seriename\Season01, results in the files being placed in E:\Videos\Seriename\torrent-orinal-destination-folder-name.
In the pre beta the result would be e:\Videos\TVSeriename\Season01\filename.avi, this is what we had and need back. Also the history stored is not stored properly, last folder is also not saved/used. wrong destinations are used over and over again, Resulting in having to move and reorganise files when done seeding.

**Comment by whirm** [comment]
You mean that when you add a multi file download, it will create a directory for all the files on that torrent instead of mixing them up with whatever you had on the selected target dir?

**Comment by Nubro01** [comment]
When I pick a location like e:\Videos\TVSeries\SerieName\Season01 then the pre beta version would put all the selected files from that Torrent in that folder. Normally I would only select the avi file that I want and not all the other noncense files. The result would be that folder Season01 would contain all the selected files from the torrent. Since the beta the last folder is not used,and within SerieName a folder is created with the name of the Torrent and within that folder all selected files are created.
I would geuss that if you try it yourself that the same should happen, or not?

**Comment by whirm** [comment]
Ah, I get it now. 

Thanks for your report!

**Comment by whirm** [comment]
@Nubro01 I've fixed the dropping the last path component issue. 

What's missing is the possibility to select only a file on the torrent and make Tribler not create a torrent dir. only for it. I won't be doing this for 6.5 but feel free to create a feature request for that and we can think of a way to not make it confusing for the end user.

Thanks!

**Comment by Nubro01** [comment]
This is still NOT FIXED within 6.5.1, your changes where probably overwritten.

**Comment by whirm** [comment]
I'm on vacation, @devos50 or @lfdversluis could you see if this is not fixed on `devel` either?
