### ISSUE TITLE
[7.5.0] RuntimeError: [Failure instance: Traceback: <class 'TypeError'>: ord() expected string of length 1, but int found

### ISSUE THREAD

**Issue by devos50** [Tribler/tribler#5090]
From the error reporter:

```
Traceback (most recent call last):
File "TriblerGUI\event_request_manager.py", line 114, in on_read_data
RuntimeError: [Failure instance: Traceback: <class 'TypeError'>: ord() expected string of length 1, but int found
lib\site-packages\twisted\internet\base.py:1283:run
lib\site-packages\twisted\internet\base.py:1292:mainLoop
lib\site-packages\twisted\internet\base.py:913:runUntilCurrent
lib\site-packages\twisted\internet\task.py:239:__call__
--- <exception caught here> ---
lib\site-packages\twisted\internet\defer.py:151:maybeDeferred
Tribler\Core\Libtorrent\LibtorrentMgr.py:569:_task_process_alerts
Tribler\Core\Libtorrent\LibtorrentMgr.py:396:process_alert
Tribler\Core\Libtorrent\__init__.py:17:invoke_func
Tribler\Core\Libtorrent\LibtorrentDownloadImpl.py:492:process_alert
Tribler\Core\Libtorrent\LibtorrentDownloadImpl.py:594:on_metadata_received_alert
Tribler\Core\Libtorrent\LibtorrentDownloadImpl.py:688:set_corrected_infoname
Tribler\Core\TorrentDef.py:317:get_name_as_unicode
Tribler\Core\TorrentDef.py:316:filter_characters
Tribler\Core\TorrentDef.py:316:<listcomp>
Tribler\Core\TorrentDef.py:311:filter_character
]
```

**Comment by devos50** [comment]
This failed again in Tribler 7.5.0 (with a similar stack trace):

```
Traceback (most recent call last):
File "src\tribler-gui\tribler_gui\event_request_manager.py", line 112, in on_read_data
RuntimeError: ord() expected string of length 1, but int found
--LONG TEXT--
Traceback (most recent call last):
File "lib\asyncio\events.py", line 88, in _run
File "ipv8\taskmanager.py", line 123, in done_cb
File "ipv8\taskmanager.py", line 17, in interval_runner
File "lib\asyncio\coroutines.py", line 120, in coro
File "src\tribler-core\tribler_core\modules\libtorrent\download_manager.py", line 450, in _task_process_alerts
File "src\tribler-core\tribler_core\modules\libtorrent\download_manager.py", line 342, in process_alert
File "src\tribler-core\tribler_core\modules\libtorrent\download.py", line 219, in process_alert
File "src\tribler-core\tribler_core\modules\libtorrent\download.py", line 270, in on_save_resume_data_alert
File "src\tribler-core\tribler_core\modules\libtorrent\torrentdef.py", line 318, in get_name_as_unicode
File "src\tribler-core\tribler_core\modules\libtorrent\torrentdef.py", line 317, in filter_characters
File "src\tribler-core\tribler_core\modules\libtorrent\torrentdef.py", line 317, in <listcomp>
File "src\tribler-core\tribler_core\modules\libtorrent\torrentdef.py", line 312, in filter_character
TypeError: ord() expected string of length 1, but int found
--CONTEXT--
{'message': "Exception in callback TaskManager.register_task.<locals>.done_cb(<Task finishe...t int found')>) at ipv8\\taskmanager.py:120", 'exception': TypeError('ord() expected string of length 1, but int found'), 'handle': <Handle TaskManager.register_task.<locals>.done_cb(<Task finishe...t int found')>) at ipv8\taskmanager.py:120>}
```

**Comment by qstokkink** [comment]
Seems like `self.metainfo[b"info"][b"name"]` is already a `bytes` object.

**Comment by egbertbouman** [comment]
This was fixed in https://github.com/Tribler/tribler/pull/5092/commits/db92b262e76b8c788e9ad8fec4a2a2636be50f2f and made its way into v7.4.2, but now it's back somehow. I'll fix it again, and I'll add a unit test this time.

**Comment by devos50** [comment]
Unfortunately, #5405 does not seem to fix the issue. As reported multiple times in 7.5.1:

```
Traceback (most recent call last):
File "src\tribler-gui\tribler_gui\event_request_manager.py", line 112, in on_read_data
RuntimeError: ord() expected string of length 1, but int found
--LONG TEXT--
Traceback (most recent call last):
File "lib\asyncio\events.py", line 88, in _run
File "ipv8\taskmanager.py", line 123, in done_cb
File "ipv8\taskmanager.py", line 17, in interval_runner
File "lib\asyncio\coroutines.py", line 120, in coro
File "src\tribler-core\tribler_core\modules\libtorrent\download_manager.py", line 450, in _task_process_alerts
File "src\tribler-core\tribler_core\modules\libtorrent\download_manager.py", line 342, in process_alert
File "src\tribler-core\tribler_core\modules\libtorrent\download.py", line 219, in process_alert
File "src\tribler-core\tribler_core\modules\libtorrent\download.py", line 270, in on_save_resume_data_alert
File "src\tribler-core\tribler_core\modules\libtorrent\torrentdef.py", line 318, in get_name_as_unicode
File "src\tribler-core\tribler_core\modules\libtorrent\torrentdef.py", line 317, in filter_characters
File "src\tribler-core\tribler_core\modules\libtorrent\torrentdef.py", line 317, in <listcomp>
File "src\tribler-core\tribler_core\modules\libtorrent\torrentdef.py", line 312, in filter_character
TypeError: ord() expected string of length 1, but int found
--CONTEXT--
{'message': "Exception in callback TaskManager.register_task.<locals>.done_cb(<Task finishe...t int found')>) at ipv8\\taskmanager.py:120", 'exception': TypeError('ord() expected string of length 1, but int found'), 'handle': <Handle TaskManager.register_task.<locals>.done_cb(<Task finishe...t int found')>) at ipv8\taskmanager.py:120>}
```

**Comment by qstokkink** [comment]
Uhh.. but the `ord()` function is not on that line? See: https://github.com/Tribler/tribler/blob/release-7.5/src/tribler-core/tribler_core/modules/libtorrent/torrentdef.py#L312

Only `devel` has the `ord()` function there.

**Comment by egbertbouman** [comment]
I just downloaded the v7.5.1 and decompiled `TorrentDef`, and the `ord()` call is still there. Maybe something went wrong while building the release?

**Comment by egbertbouman** [comment]
Turns out the v7.5.1 tag was made before the fix was merged.

**Comment by qstokkink** [comment]
Alright, then this issue is fixed, just not released.

**Comment by Dmole** [comment]
> Turns out the v7.5.1 tag was made before the fix was merged.

Is there a link to a working build?

**Comment by qstokkink** [comment]
@Dmole that particular traceback is fixed in the 7.6 series (first pre-release out now: https://github.com/Tribler/tribler/releases/tag/v7.6.0-exp1).
