### ISSUE TITLE
Strange empty dialog window

### ISSUE THREAD

**Issue by ichorid** [Tribler/tribler#5443]
Ubuntu 20.04, Tribler 7.5.1, just left it for some time on the "Downloads" screen.
![изображение](https://user-images.githubusercontent.com/2509103/86478599-c2b39500-bd4a-11ea-85aa-1591a002368e.png)

Buttons on the left a clickable still. The Core runs fine.

:shrug:

**Comment by hbiyik** [comment]
that happens when run with python3.8, was there for a while in 7.5 branch dont know why though.

**Comment by ichorid** [comment]
So, it is not just my machine. @hbiyik , thanks for reporting.

**Comment by hbiyik** [comment]
I observed that this only happens when there is a download in downloading state

**Comment by hbiyik** [comment]
No this only happens when i minimise the window and maximise again, dont know why though. My qt version is 5.14.1

**Comment by devos50** [comment]
Hmm interesting. Sounds like something Qt-related. Does it happen everytime for you?

**Comment by hbiyik** [comment]
yes, i can provide remote session if you want

**Comment by ichorid** [comment]
Haven't seen it in a while. I suspect this is the result of some incompatibility between PyQt bindings and Debian QT libs. Closing it for now. Feel free to reopen as necessaryl

**Comment by hbiyik** [comment]
yes it is fixed in latest devel.

**Comment by hbiyik** [comment]
oh no, it is there again on devel branch

**Comment by xoriole** [comment]
@hbiyik Can you still reproduce this on `main` branch or `7.10.0` release?

**Comment by hbiyik** [comment]
nope its gone.

**Comment by xoriole** [comment]
Great! closing this issue
